### ISSUE TITLE
Rules setting in .stylelintrc ?

### ISSUE THREAD

**Issue by stela5** [AtomLinter/linter-stylelint#10]
I'd like to implement Rules settings as indicated on https://github.com/stylelint/stylelint -- something like:

```
{
  "rules": {
    "rule-no-single-line": 0, // turn rule off
    "declaration-no-important": 2, // turn rule on
  }
}
```

I get an error when I put that in *.stylelintrc* -- *SyntaxError: Unexpected token*

Am I doing it wrong?

**Comment by 1000ch** [comment]
@stela5 Oops, would you update `linter-stylelint` to newest?
And, you have to remove comments (`//`) in JSON file.

**Comment by stela5** [comment]
@1000ch I'm running version 1.0.5 with the following **.stylelintrc** file:

```
{
  "rules": {
    "at-rule-empty-line-before": 0,
    "color-hex-case": 0
  }
}
```

Those warnings still appear, though.  If I uncheck *Use preset* in the settings all syntax checking stops.  Thoughts?

**Comment by stela5** [comment]
Same behavior on v1.0.6 with this .stylelintrc file:

```
{
  "rules": {
    "property-no-vendor-prefix": 0
  }
}
```

**Comment by 1000ch** [comment]
Umm, it works. Does anyone have same behavior?

**Comment by stela5** [comment]
It could be machine-specific, but here are some screenshots in case they help:

http://s27.postimg.org/iu9rpwopf/image.png
http://s13.postimg.org/6d5n18rfr/image.png
http://s15.postimg.org/tl8ni4l6z/image.png

**Comment by stela5** [comment]
I think I'm getting closer.  I disabled *Use preset* on the config screen to activate the  `.stylelintrc` file:

```
{
  "rules": {
    "at-rule-empty-line-before": 2
  }
}
```

And now it throws this stack error:

```
Uncaught TypeError: Invalid Point: (NaN, NaN)
C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\point.js:65
Hide Stack Trace
TypeError: Invalid Point: (NaN, NaN)
  at Function.module.exports.Point.assertValid (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:982:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:970:20)
  at TextBuffer.module.exports.TextBuffer.markRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:695:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\src\display-buffer.js:1403:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\src\text-editor.js:1285:59)
  at C:\Users\myusername\.atom\packages\linter\lib\editor-linter.js:60:33
  at Emitter.module.exports.Emitter.emit (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at EditorLinter.addMessage (C:\Users\myusername\.atom\packages\linter\lib\editor-linter.js:132:22)
  at C:\Users\myusername\.atom\packages\linter\lib\linter-views.coffee:49:20
```

**Comment by stela5** [comment]
P.S. I also tried copying the JSON object from https://github.com/stylelint/stylelint-config-suitcss/blob/master/index.js into my `.stylelintrc` file but more stack errors were thrown because it doesn't look like that JSON structure is well-formed (trailing commas, etc.).  Thoughts?

**Comment by stela5** [comment]
Ref https://github.com/AtomLinter/linter-csslint/issues/37

**Comment by 1000ch** [comment]
Thank you for debugging :+1: I will fix this in a few days...

**Comment by stela5** [comment]
Glad to help!  I really like this plugin and I think we're really close to having it work perfectly for my needs.  My biggest hurdle was figuring out that I had to define *all* my rules from scratch (both active and inactive) when disabling the preset.

P.S. The error sometimes references this issue post: https://github.com/atom-community/linter/issues/804

**Comment by 1000ch** [comment]
@stela5 

>I think I'm getting closer. I disabled Use preset on the config screen to activate the following .stylelintrc file:
>```json
>{
>  "rules": {
>    "at-rule-empty-line-before": 2
>  }
>}
>```
>And now it throws this stack error:

It may be error of linter core own.

**Comment by 1000ch** [comment]
It works by checking *Use Preset* off and put `.stylelintrc` such as following.

```json
{
  "rules": {
    "at-rule-no-vendor-prefix": 2,
    "block-closing-brace-newline-after": [ 2, "always" ],
    "block-closing-brace-newline-before": [ 2, "always-multi-line" ],
    "block-closing-brace-space-before": [ 2, "always-single-line" ],
    "block-no-empty": 2,
    "block-opening-brace-newline-after": [ 2, "always-multi-line" ],
    "block-opening-brace-space-after": [ 2, "always-single-line" ],
    "block-opening-brace-space-before": [ 2, "always" ],
    "color-hex-case": [ 2, "lower" ],
    "color-hex-length": [ 2, "short" ],
    "color-no-invalid-hex": 2,
    "comment-empty-line-before": [ 2, "always" ],
    "declaration-bang-space-after": [ 2, "never" ],
    "declaration-bang-space-before": [ 2, "always" ],
    "declaration-block-semicolon-newline-after": [ 2, "always-multi-line" ],
    "declaration-block-semicolon-space-after": [ 2, "always-single-line" ],
    "declaration-block-semicolon-space-before": [ 2, "never" ],
    "declaration-colon-space-after": [ 2, "always" ],
    "declaration-colon-space-before": [ 2, "never" ],
    "function-calc-no-unspaced-operator": 2,
    "function-comma-space-after": [ 2, "always" ],
    "function-comma-space-before": [ 2, "never" ],
    "function-parentheses-space-inside": [ 2, "never" ],
    "function-space-after": [ 2, "always" ],
    "function-url-quotes": [ 2, "double" ],
    "indentation": [ 2, 2 ],
    "media-feature-colon-space-after": [ 2, "always" ],
    "media-feature-colon-space-before": [ 2, "never" ],
    "media-feature-name-no-vendor-prefix": 2,
    "media-feature-range-operator-space-after": [ 2, "always" ],
    "media-feature-range-operator-space-before": [ 2, "always" ],
    "media-query-list-comma-newline-after": [ 2, "always-multi-line" ],
    "media-query-list-comma-space-after": [ 2, "always-single-line" ],
    "media-query-list-comma-space-before": [ 2, "never" ],
    "media-query-parentheses-space-inside": [ 2, "never" ],
    "nesting-block-opening-brace-newline-before": [ 2, "always-multi-line" ],
    "nesting-block-opening-brace-space-before": [ 2, "always-single-line" ],
    "no-eol-whitespace": 2,
    "no-missing-eof-newline": 2,
    "no-multiple-empty-lines": 2,
    "number-leading-zero": [ 2, "always" ],
    "number-no-trailing-zeros": 2,
    "number-zero-length-no-unit": 2,
    "property-no-vendor-prefix": 2,
    "root-no-standard-properties": 2,
    "rule-no-shorthand-property-overrides": 2
  }
}
```

And you? @stela5

**Comment by stela5** [comment]
Agreed, this must be a core linter issue: https://github.com/atom-community/linter/issues?utf8=%E2%9C%93&q=is%3Aissue+nan

It's strange because it only gets thrown with **at-rule-empty-line-before**.  If I use your *.stylelintrc* file above, everything works fine.  But if I use

```
{
  "rules": {
    "at-rule-no-vendor-prefix": 2,
    "at-rule-empty-line-before": 2
  }
}
```

on a barebones CSS file that doesn't even have an at-rule

```
body {
  margin: 0;
}
```

I still throws an error.

```
Uncaught TypeError: Invalid Point: (NaN, NaN)
C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\point.js:65
Hide Stack Trace
TypeError: Invalid Point: (NaN, NaN)
  at Function.module.exports.Point.assertValid (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:982:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:970:20)
  at TextBuffer.module.exports.TextBuffer.markRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:695:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\src\display-buffer.js:1403:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\src\text-editor.js:1285:59)
  at C:\Users\myusername\.atom\packages\linter\lib\editor-linter.js:60:33
  at Emitter.module.exports.Emitter.emit (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at EditorLinter.addMessage (C:\Users\myusername\.atom\packages\linter\lib\editor-linter.js:132:22)
  at C:\Users\myusername\.atom\packages\linter\lib\linter-views.coffee:49:20
  at Array.forEach (native)
  at LinterViews.notifyEditors (C:\Users\myusername\.atom\packages\linter\lib\linter-views.coffee:46:11)
  at LinterViews.render (C:\Users\myusername\.atom\packages\linter\lib\linter-views.coffee:39:6)
  at C:\Users\myusername\.atom\packages\linter\lib\linter.coffee:29:14
  at Emitter.module.exports.Emitter.emit (C:\Users\myusername\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at MessageRegistry.updatePublic (C:\Users\myusername\.atom\packages\linter\lib\message-registry.js:116:20)
  at UpdateMessages (C:\Users\myusername\.atom\packages\linter\lib\message-registry.js:42:17)

The error was thrown from the linter package. This issue has already been reported.
```

**Comment by Arcanemagus** [comment]
The Invalid Point (NaN, NaN) message is most likely this provider attempting to send a message to `linter` without a proper range specified. Possibly due to that rule's specific error message not having a line or column attribute?

Before you submit a bug to `linter` I would verify that the range is valid for that message.

**Comment by stela5** [comment]
@1000ch thoughts?

**Comment by stela5** [comment]
Yay, I finally figured it out.  I didn't realize that some eslint rules **require options**.

For example, https://github.com/stylelint/stylelint/blob/master/src/rules/at-rule-no-vendor-prefix/index.js#L16 is very forgiving and if you use `"at-rule-no-vendor-prefix": 2,` it works perfectly fine.  However, https://github.com/stylelint/stylelint/blob/master/src/rules/at-rule-empty-line-before/index.js#L19 is less forgiving and `"at-rule-empty-line-before": 2` will throw an error but `"at-rule-empty-line-before": [ 2, "always" ]` works.

I guess the moral of the story is to use one of the three provided presets  :)

That said, some CSS frameworks throw a lot of warnings that are burying my own CSS issues so perhaps it might be useful to have a few presets that only throw errors (if they exist) instead of warnings (level 2).

**Comment by 1000ch** [comment]
@Arcanemagus OK, I'll make sure that which causes the problem.
@stela5 Thank you for debugging. It's OK if `.stylelintrc` is valid, isn't it?

**Comment by davidtheclark** [comment]
@stela5 : Yeah, *most* stylelint rules require both a severity and a primary option, so `rule-name: [ severity, primary ]`. Only the `*-no-*` rules do not require the primary option, because the "no" in the rule name already sets the expectation for you.

**Comment by stela5** [comment]
@1000ch Yes, everything is okay if `.stylelintrc` is valid.  Working as intended.

**Comment by benfrain** [comment]
If I use my own config and place it in an .stylelintrc file in the project root:

````
{
    "rules": {
        "block-no-empty": 2,
        "color-no-invalid-hex": 2,
        "declaration-colon-space-after": [2, "always"],
        "declaration-colon-space-before": [2, "never"],
        "function-comma-space-after": [2, "always"],
        "function-url-quotes": [2, "double"],
        "media-feature-colon-space-after": [2, "always"],
        "media-feature-colon-space-before": [2, "never"],
        "media-feature-name-no-vendor-prefix": 2,
        "no-multiple-empty-lines": 2,
        "number-leading-zero": [2, "never"],
        "number-no-trailing-zeros": 2,
        "property-no-vendor-prefix": 2,
        "rule-no-duplicate-properties": 2,
        "rule-no-single-line": 2,
        "rule-trailing-semicolon": [2, "always"],
        "selector-list-comma-newline-after": [2, "always-multi-line"],
        "selector-no-id": 2,
        "string-quotes": [2, "double"],
        "value-no-vendor-prefix": 2
    }
}
````

Or if I use the one by @1000ch here: https://github.com/AtomLinter/linter-stylelint/issues/10#issuecomment-147974943

I get one of two things happening. If I uncheck the 'preset' then nothing happens. Despite errors I don't get stylelint doing its thing. If I leave it checked I get this blow up:

````
Invalid .stylelintrc
Failed to parse .stylelintrc JSON
````
````
ReferenceError: error is not defined
ReferenceError: error is not defined
    at Object.lint (/Users/benfrain/.atom/packages/linter-stylelint/index.js:81:25)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/benfrain/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/benfrain/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/benfrain/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/benfrain/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/benfrain/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/benfrain/.atom/packages/linter/lib/helpers.coffee:23:18
```` 

This is the only linter I have installed currently (running Atom 1.3.1).
