### ISSUE TITLE
Column start (2) greater than line length (1) Error

### ISSUE THREAD

**Issue by ismay** [AtomLinter/linter-stylelint#143]
I'm getting the following error with linter-stylelint:

```
Error: Column start (2) greater than line length (1)
    at rangeFromLineNumber (C:\Users\ismay.DEFACTO\.atom\packages\linter-stylelint\node_modules\atom-linter\lib\index.js:195:11)
    at createRange (C:/Users/ismay.DEFACTO/.atom/packages/linter-stylelint/lib/index.js:35:10)
    at C:/Users/ismay.DEFACTO/.atom/packages/linter-stylelint/lib/index.js:74:14
    at Array.map (native)
    at stylelint.lint.then.error.type (C:/Users/ismay.DEFACTO/.atom/packages/linter-stylelint/lib/index.js:70:38)
```

With this `.stylelintrc`:

```
{
  "extends": [
    "stylelint-config-suitcss"
  ],
  "plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    "selector-bem-pattern": {
      "preset": "suit"
    }
  }
}

```

For the following file (apologies for the large amount of text):

```
/** @define Button */

/*
Button

The basic button upon which all button styles are built. Buttons should always have the `.Button--default` class.
Intentionally minimalistic and not meant to be used on its own.

Markup:
<a class="Button Button--default {{modifier_class}}">Link</a>
<button class="Button Button--default {{modifier_class}}">Button</button>
<input type="submit" class="Button Button--default {{modifier_class}}" value="Input">

Styleguide Components.Button
*/

.Button--default {
  border: none;
  border-radius: 0.25rem;
  text-transform: uppercase;
  padding: 0.5rem 1rem;
}

/*
Button--tab

Deprecated: Buttons to use for tabbed navigation. Deprecated because it shares functionality with the
navigation buttons. Should be refactored to a single type.

:hover - Fades to a dark background and white text
:focus - Same as hover, with an outline as well
:active - Same as hover
.isActive - Same as hover

Markup:
<a class="Button Button--default Button--tab {{modifier_class}}">Link</a>
<button class="Button Button--default Button--tab {{modifier_class}}">Button</button>
<input type="submit" class="Button Button--default Button--tab {{modifier_class}}" value="Input">

Styleguide Components.Button.Tab
*/

.Button--tab {
  background: var(--white);
  color: var(--gray);
  border-radius: 0;
  line-height: 2;
  font-weight: 600;
  transition: var(--transition);
}

.Button--tab:hover,
.Button--tab:focus,
.Button--tab:active,
.Button--tab.isActive {
  background: var(--gray);
  color: var(--white);
}

/*
Button--red

Deprecated: A red button. Useful for actions that are dangerous, like deleting something. Should be replaced
by a `Button--danger`.

:hover - Lightens the whole button
:focus - Same as hover, with an outline as well
:active - Same as hover

Markup:
<a class="Button Button--default Button--red {{modifier_class}}">Link</a>
<button class="Button Button--default Button--red {{modifier_class}}">Button</button>
<input type="submit" class="Button Button--default Button--red {{modifier_class}}" value="Input">

Styleguide Components.Button.Red
*/

.Button--red {
  background: var(--red);
  transition: var(--transition);
  color: var(--white);
  font-weight: 600;
  font-size: 0.75rem;
  transition: var(--transition);
}

.Button--red:hover,
.Button--red:focus,
.Button--red:active {
  background: var(--red-light);
}

/*
Button--green

Deprecated: A green button. Useful for positive actions, like adding or saving something. Should be replaced
by a `Button--success`.

:hover - Lightens the whole button
:focus - Same as hover, with an outline as well
:active - Same as hover

Markup:
<a class="Button Button--default Button--green {{modifier_class}}">Link</a>
<button class="Button Button--default Button--green {{modifier_class}}">Button</button>
<input type="submit" class="Button Button--default Button--green {{modifier_class}}" value="Input">

Styleguide Components.Button.Green
*/

.Button--green {
  background: var(--green);
  transition: var(--transition);
  color: var(--white);
  font-weight: 600;
  font-size: 0.75rem;
  transition: var(--transition);
}

.Button--green:hover,
.Button--green:focus,
.Button--green:active {
  background: var(--green-light);
}

/*
Button--border

A button with a border and a transparent background.

:hover - Inverts the button colors
:focus - Same as hover, with an outline as well
:active - Same as hover
.isActive - Same as hover

Markup:
<a class="Button Button--default Button--border {{modifier_class}}">Link</a>
<button class="Button Button--default Button--border {{modifier_class}}">Button</button>
<input type="submit" class="Button Button--default Button--border {{modifier_class}}" value="Input">

Styleguide Components.Button.Border
*/

.Button--border {
  border: 1px solid var(--gray);
  color: var(--blue-dark);
  font-weight: 600;
  font-size: 0.75rem;
  transition: var(--transition);
}

.Button--border:hover,
.Button--border:focus,
.Button--border:active,
.Button--border.isActive {
  color: var(--white);
  background: var(--gray);
}

/*
Button--text

Deprecated: A text button. Originally meant to look like text, but that isn't really what you want because
users won't know that it's a link. To be removed.

Markup:
<a class="Button Button--default Button--text">Link</a>
<button class="Button Button--default Button--text">Button</button>
<input type="submit" class="Button Button--default Button--text" value="Input">

Styleguide Components.Button.Text
*/

.Button--text {
  font-family: var(--body-condensed);
  text-transform: none;
  padding: 0;
}

/*
Button--subtle

Deprecated: A button that looks different from text but blends in with the background to not stand out too much.

:hover - Inverts the button colors
:focus - Same as hover, with an outline as well
:active - Same as hover
.isActive - Same as hover

Markup:
<a class="Button Button--default Button--subtle {{modifier_class}}">Link</a>
<button class="Button Button--default Button--subtle {{modifier_class}}">Button</button>
<input type="submit" class="Button Button--default Button--subtle {{modifier_class}}" value="Input">

Styleguide Components.Button.Subtle
*/

.Button--subtle {
  color: var(--gray);
  font-weight: 600;
  font-size: 0.75rem;
  transition: var(--transition);
}

.Button--subtle:hover,
.Button--subtle:focus,
.Button--subtle:active,
.Button--subtle.isActive {
  color: var(--white);
  background: var(--gray);
}

/*
Button--status

Deprecated: A button with a fixed width, meant to lessen the jarring effect of the transition between
two button styles with different widths. Should be solved differently as it is likely to break because
of the fixed width.

Markup:
<a class="Button Button--default Button--status">Link</a>
<button class="Button Button--default Button--status">Button</button>
<input type="submit" class="Button Button--default Button--status" value="Input">

Styleguide Components.Button.Status
*/

.Button--status {
  min-width: 11em;
}

/*
Button--nav

Deprecated: A button meant only for navigation links. Meant to be used on a dark background. Deprecated because it
shares functionality with the tab buttons. Should be refactored to a single type.

:hover - Brightens the background a little.
:focus - Same as hover, with an outline as well
:active - Same as hover
.isActive - Same as hover

Markup:
<div style="background: gray;">
  <a class="Button Button--default Button--nav {{modifier_class}}">Link</a>
  <button class="Button Button--default Button--nav {{modifier_class}}">Button</button>
  <input type="submit" class="Button Button--default Button--nav {{modifier_class}}" value="Input">
</div>

Styleguide Components.Button.Navigation
*/

.Button--nav {
  border-radius: 0;
  line-height: 3;
  color: var(--white);
  font-weight: 600;
  font-size: 0.75rem;
  transition: var(--transition);
}

.Button--nav:hover,
.Button--nav:focus,
.Button--nav:active,
.Button--nav.isActive {
  color: var(--white);
  background: var(--white-transparent);
}


/*
Button--sort

Deprecated: The sorting buttons have arrow designating the current sorting direction. The `sort-asc` and `sort-desc` classes
are used to hide the arrows on inital load. This should be refactored to more global classes as this is too specific.

Markup:
<a class="Button Button--default Button--sort-asc">Link</a>
<a class="Button Button--default Button--sort-desc">Link</a>

Styleguide Components.Button.Sort
*/

.Button--sort-asc,
.Button--sort-desc {
  display: none;
}

/*
Button--bar

Deprecated: This is currently only used in one location (ItemFooter). The padding this class applies is to compensate for the absence
of padding on its parent section. This should be done differently as its too dependent on its context. Should be refactored to a full-width
modifier.

Markup:
<a class="Button Button--default Button--bar">Link</a>
<button class="Button Button--default Button--bar">Button</button>
<input type="submit" class="Button Button--default Button--bar" value="Input">

Styleguide Components.Button.Bar
*/

.Button--bar {
  padding: 1rem;
}

/*
Button--dropdown

Deprecated: This button was specifically meant to be used for triggering the sorting dropdown. Only used in one location
and it looks like text instead of a button. Should be refactored to a more global style and look more like a button.

Markup:
<a class="Button Button--default Button--dropdown">Link</a>
<button class="Button Button--default Button--dropdown">Button</button>
<input type="submit" class="Button Button--default Button--dropdown" value="Input">

Styleguide Components.Button.Dropdown
*/

.Button--dropdown {
  color: var(--gray);
  font-weight: 600;
  font-size: 0.75rem;
}
```

Might be related to this issue: https://github.com/AtomLinter/linter-eslint/issues/322?

**Comment by Arcanemagus** [comment]
Not related, this is just a message that is returned from the common helper library when an invalid line/col is sent to it for generation of a range.

Looking into this now.

**Comment by Arcanemagus** [comment]
Hmmmm, I can't reproduce that with this setup: [linter-stylelint_GH143.zip](https://github.com/AtomLinter/linter-stylelint/files/206984/linter-stylelint_GH143.zip)

Are you possibly not on the latest version of `linter-stylelint`? It looks like you've ran into issues [before](https://github.com/AtomLinter/linter-stylelint/issues/134) with `stylelint-selector-bem-pattern`.

**Comment by Arcanemagus** [comment]
.....and all of the issue content just disappeared???

**Comment by ismay** [comment]
@Arcanemagus Whoa, that's weird! I didn't edit it. I'm not at work now, so I can't reproduce the error, but I'll do so tomorrow.

As for the version, I've done a fresh install of all the packages (even of atom), but maybe atom reused old packages after the reinstall? I'll try reinstalling the plugin, will let you know if that helps.

**Comment by Arcanemagus** [comment]
Even stranger, the audit log on the organization shows no record of the edit :confused:

Anyway, the zip file contains the state of the configuration before it disappeared...

**Comment by Arcanemagus** [comment]
Looks like it was a bug with assigning the (ironically: `bug`) label: https://status.github.com/messages

Also apparently there is no audit log for the description, only comments.

**Comment by ismay** [comment]
Ah ok 😋

**Comment by Arcanemagus** [comment]
Were you able to reproduce this @ismay?

**Comment by ismay** [comment]
You mean after updating linter-stylelint right? 

> Are you possibly not on the latest version of linter-stylelint? It looks like you've ran into issues before with stylelint-selector-bem-pattern.

Yeah it did occur again periodically, not sure what's triggering it. I'll do some more isolated testing on monday while at work, which is where I'm running into this. Will report back with the results.

**Comment by ismay** [comment]
After some testing I'm no longer able to reproduce it. I think we can close this, should I encounter it again I'll let you know.

**Comment by Arcanemagus** [comment]
Okay, if you see it again immediately save the file in that state, run `stylelint` on it from a CLI and see if you can spot the line that is off and report it, we can work out where the issue is from there.
