### ISSUE TITLE
Failed to activate the linter-stylelint package

### ISSUE THREAD

**Issue by luciy** [AtomLinter/linter-stylelint#178]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) package, v2.7.0

### Stack Trace

Failed to activate the linter-stylelint package

```
At Cannot find module 'lazy-req'

Error: Cannot find module 'lazy-req'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/luciy/.atom/packages/linter-stylelint/lib/index.js:3:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "cht-menu"
    ]
  },
  "linter-stylelint": {
    "disableWhenNoConfig": true
  }
}
```

### Installed Packages

```coffee
# User
atom-chs-menu, v1.0.0
atom-ternjs, v0.14.1
autocomplete-paths, v1.0.2
emmet, v2.4.3
file-icons, v1.7.7
linter, v1.11.4
linter-eslint, v7.2.1
linter-stylelint, v2.7.0
minimap, v4.23.1
open-recent, v5.0.0
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like you've hit the infamous bug with `apm` where it doesn't install all the dependencies. Can you try re-installing the package?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

**Comment by langpavel** [comment]
Reinstalling just works
