### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by sambev** [AtomLinter/linter-stylelint#24]
1. Open a css file.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.2

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, NaN)

```
At /Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, NaN)
    at Function.module.exports.Point.assertValid (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:980:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:968:20)
    at TextBuffer.module.exports.TextBuffer.markRange (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:693:46)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1065:41)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1267:59)
    at /Users/sambev/.atom/packages/linter/lib/editor-linter.js:50:34
    at Emitter.module.exports.Emitter.emit (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at EditorLinter.addMessage (/Users/sambev/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/sambev/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/sambev/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/sambev/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/sambev/.atom/packages/linter/lib/linter.coffee:39:14
    at Emitter.module.exports.Emitter.emit (/Users/sambev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at MessageRegistry.updatePublic (/Users/sambev/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/sambev/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flow"
    ]
  },
  "linter": {
    "lintOnFlyInterval": 500
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
language-babel, v2.3.0
linter, v1.11.2
linter-eslint, v5.2.4
linter-jsonlint, v1.0.1
linter-stylelint, v1.3.0
minimap, v4.16.2
pigments, v0.19.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Do you have an example file to test trigger this? Or does it happen for you on _every_ file?

**Comment by sambev** [comment]
I do use postcss syntax for most of my files but it will happen on any kind of css file

**Comment by Arcanemagus** [comment]
I'm not able to reproduce this, do you have a file that you can share that triggers this?

If not, when you run into this can you put a breakpoint in `linter-stylelint` right before it returns its messages and see if any of the ranges are invalid?

**Comment by 1000ch** [comment]
@sambev Would you paste CSS example that reproduce this problem?

**Comment by sambev** [comment]
@1000ch Sure.

```css
.test-list {
    background-color: red;
}
```

@Arcanemagus I'll try to get into the error a bit more on Monday and post the results. Thanks!

**Comment by sambev** [comment]
@Arcanemagus looks like my ranges are indeed invalid.
![screen shot 2015-11-30 at 9 36 18 am](https://cloud.githubusercontent.com/assets/2127504/11477571/d7a8d860-9745-11e5-9475-deee8140e4db.png)

The errors look to be errors with my stylelintrc e.g. I had `'long'` as a value for `color-hex-case`. I am working on fixing them (I can inspect the message objects before the exception).

**Comment by sambev** [comment]
It looks like after I cleaned up the errors in my stylelintrc file, it's working great.

**Comment by Arcanemagus** [comment]
Yea, that's what is done with other linters, we just create a dummy range encompassing the first line of the file.

**Comment by satazor** [comment]
@Arcanemagus I was just by this issue.. I had errors in my stylelint that led to this. Do you accept a PR to mock line, column, etc?

**Comment by Arcanemagus** [comment]
Of course :wink:

**Comment by satazor** [comment]
@Arcanemagus this is actually more complex than the original issue.

There is three kind of errors that might happen:

1 - Invalid syntax of .stylelintrc which cosmic config will detected (this is showing a error notification atm)
2 - Error thrown by stylelint when a fatal error exists, e.g. specifying "extends" pointing to an invalid package (this is being ignored atm)
3 - The actual error describe error, where we have a rule with an invalid option that causes line and column to be undefined

How does the other linters deal with 1 and 2 error? Looking at the source code of some of them, I think they simply return a promise that will fail, which causes a error notification to popup. Imho we should do the same.
For 3, we simply patch line and column to display the error at the beginning of the file as suggested.

Thoughts?

**Comment by satazor** [comment]
This issue can now be closed
