### ISSUE TITLE
Cannot read property 'findFile' of undefined when opening or saving

### ISSUE THREAD

**Issue by MadLittleMods** [AtomLinter/linter-stylelint#26]
I get the following error when opening or saving a file:

```
TypeError: Cannot read property 'findFile' of undefined
    at Object.lint (/Users/Eastwood/.atom/packages/linter-stylelint/index.js:67:8)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/Eastwood/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/Eastwood/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/Eastwood/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/Eastwood/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/Eastwood/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/Eastwood/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by Arcanemagus** [comment]
Which version are you on? I recently pushed out v1.3.2 which should fix this.

**Comment by MadLittleMods** [comment]
I did update `v1.3.2` on Atom v1.2.4 but I must of not reopened the file for it to kick in. Everything seems to be good now after a restart.

**Comment by Arcanemagus** [comment]
Yea sometimes Atom is a bit buggy with updates and will require a restart of Atom for them to take effect. Glad to hear that fixed it for you!
