### ISSUE TITLE
EvalError – 'unsafe-eval' again

### ISSUE THREAD

**Issue by Pustur** [AtomLinter/linter-stylelint#269]
I've seen this error already mentioned a few times (#90 and #116) but it was apparently resolved.
Having said this, I still have this problem.

Even just starting to type anything in my `css` files will trigger these errors.

**Atom:** 1.10.2
**linter-stylelint:** 3.2.1
**Contents of `.stylelintrc` file:**
```
{
  "extends": "stylelint-config-standard"
}
```
**Stack trace:**
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Ajv.localCompile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:130:26)
    at Ajv.resolve (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/resolve.js:53:19)
    at Object.resolveRef (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:195:21)
    at Object.generate_ref [as code] (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/ref.js:22:22)
    at Object.generate_validate [as validate] (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/validate.js:157:37)
    at Object.generate_properties [as code] (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/properties.js:198:26)
    at generate_validate (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/validate.js:230:37)
    at localCompile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:91:22)
    at Ajv.compile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:59:13)
    at _compile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:325:29)
    at getSchema (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:189:51)
    at validate (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:88:11)
    at validateSchema (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:159:19)
    at _addSchema (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:285:7)
    at Ajv.compile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:110:21)
    at Ajv.addKeyword (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/keyword.js:46:40)
    at defFunc (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv-keywords/keywords/typeof.js:37:7)
    at defineKeywords (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv-keywords/index.js:20:17)
    at Object.<anonymous> (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/table/dist/validateConfig.js:29:27)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/table/dist/makeConfig.js:15:23)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/table/dist/table.js:15:19)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
```

Linting from the command line via `npm test` works fine.
Any clue?

Thanks in advance ❤️

**Comment by Arcanemagus** [comment]
Oh boy, looks like another dependency brought in by `stylelint` is attempting to `eval()` code 😞. Tracing it down now and we'll see if this is something that can be resolved there.

**Comment by Arcanemagus** [comment]
So it looks like `table` (A dependency of `stylelint`) moved to using `ajv` to validate their configuration objects with version v3.8.0, unfortunately the Ajv library `eval`s code, meaning it can't be used in any sane environment like Atom where that is blocked. I've filed https://github.com/stylelint/stylelint/issues/1912 to figure out where the responsibility of fixing this permanently should lay, but for the moment you can work around this yourself with the following:

* Install Node.js on your system if you don't already have it installed
* `cd ~/.atom/packages/linter-stylelint`
* `rm ./node_modules/table`
* `npm install table@3.7.10`

I'm going to try pushing out an update that lists that specific version of `table` as a dependency, even though it isn't used here at all, this _should_ cause it to use that version when it resolves the dependencies of `stylelint` as well.

**Comment by epoberezkin** [comment]
I will replace with Function constructor

**Comment by epoberezkin** [comment]
Eval is replaced in Ajv version 4.7.2 (that is within the range) - should be picked up next time you npm install. Please let me know if it's still an issue.

**Comment by Arcanemagus** [comment]
v3.2.2 is released which works around this for now, as commented in the `stylelint` issue v4.7.2 of Ajv doesn't actually fix this as `Function()` is just another way of evaluating unsafe code, which is blocked.

**Comment by adammockor** [comment]
Also this error is still thrown (without stack trace) if you have locally installed stylelint in your project. So you have to add `"table": "3.7.9"` to your local `package.json` to run lint inside atom.

**Comment by Arcanemagus** [comment]
This package doesn't currently support using the project's `stylelint` (https://github.com/AtomLinter/linter-stylelint/issues/51), so I'm not entirely sure how you are hitting that... does `linter-stylelint` work for you if the project doesn't have it installed locally?

**Comment by adammockor** [comment]
So on further investigation, error is still thrown when I you use `stylelint-scss` plugin. It's because plugin uses stylelint directly as it's dependency, so it brings `table@3.8.0` and runs it in context of atom.

If I remove this plugin from local dependencies, no error is shown and your atom plugin works as it should.

**Comment by Arcanemagus** [comment]
Ah ha! Very interesting, you might want to comment that over on the `stylelint` issue as it's not something I can work around here. You can "fix" it using a similar tactic to what I did here: remove your current `node_modules`, `npm install table@3.7.9`, then `npm install`.

**Comment by bjankord** [comment]
Just noting I ran into this as well on a fresh install of atom (v1.10.2). I understand this issue is essential out of your control. Thanks for the ideas on the work around.

**Comment by Arcanemagus** [comment]
`table@3.8.3` fixes this issue, I'll be pushing out a bugfix release that removes the attempt to force `table@3.7.9` later today 😉.

**Comment by bjankord** [comment]
Excited to see this fix land!

**Comment by rvetere** [comment]
yeah cool about table - but as it seems -> now it starts over with the issue by the package "ajv" in version 4.8.2 -.- i don't know yet where this problem started in their versioning

**Comment by epoberezkin** [comment]
Sorry, I don't understand what is the problem. 4.8.2 is the latest ajv version, 3.8.3 is the latest table version

**Comment by Arcanemagus** [comment]
@rvetere The current version of `table` should cause no issues, are you on the latest version of `linter-stylelint`?

**Comment by rvetere** [comment]
@Arcanemagus @epoberezkin sry guys - false alarm. somehow my node_modules were messed up. after i deleted all again and updated to table 4.8.2 - everything starts to work again perfectly 👍 

sorry for the report
