### ISSUE TITLE
Uncaught Error: Cannot find module './utils/checkAgainstRule'

### ISSUE THREAD

**Issue by julzmon** [AtomLinter/linter-stylelint#371]
[Enter steps to reproduce:]

1. Updated linter-stylelint package

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) package 4.0.2

### Stack Trace

Uncaught Error: Cannot find module './utils/checkAgainstRule'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module './utils/checkAgainstRule'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-stylelint/node_modules/stylelint/lib/index.js:3:26)
    at /packages/linter-stylelint/node_modules/stylelint/lib/index.js:33:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-stylelint/lib/helpers.js:13:18)
    at /packages/linter-stylelint/lib/helpers.js:201:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/packages/linter-stylelint/lib/index.js:13:15)
    at installLinterStylelintDeps (/packages/linter-stylelint/lib/index.js:32:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-typescript 11.0.9 
busy-signal 1.4.3 
craft-twig 0.4.0 
double-tag 0.9.0 
emmet 2.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
livestyle-atom 0.2.10 
pigments 0.40.2 
stylefmt 5.0.1 
```

**Comment by Atanacius** [comment]
I want add I have the same issue today after update :( ...

**Comment by Arcanemagus** [comment]
The current state of the package no longer has that file in the first place. Thanks for reporting this and I'm sorry it wasn't responded to earlier!
