### ISSUE TITLE
Uncaught Error: Cannot find module 'array-unique'

### ISSUE THREAD

**Issue by girard-r** [AtomLinter/linter-stylelint#401]
[Enter steps to reproduce:]

1. Install package linter-stylelint from atom IDE

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) package 4.3.0

### Stack Trace

Uncaught Error: Cannot find module 'array-unique'

```
At module.js:472

Error: Cannot find module 'array-unique'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-stylelint/node_modules/braces/index.js:8:14)
    at /packages/linter-stylelint/node_modules/braces/index.js:320:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-stylelint/node_modules/fast-glob/node_modules/micromatch/index.js:8:14)
    at /packages/linter-stylelint/node_modules/fast-glob/node_modules/micromatch/index.js:879:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-stylelint/node_modules/fast-glob/out/utils/pattern.js:16:18)
    at /packages/linter-stylelint/node_modules/fast-glob/out/utils/pattern.js:155:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
     -1:10.1.0 core:confirm (input.hidden-input)
  6x -0:38.2.0 core:backspace (input.hidden-input)
     -0:36.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-stylelint 4.3.0 
linter-ui-default 1.7.1 
```

**Comment by emuvente** [comment]
It looks like not all of the dependencies were installed correctly. Could you try reinstalling linter-stylelint and then see if you are still having this issue?

**Comment by girard-r** [comment]
I don't know why this happened.
I have uninstalled it and reinstalled it, it is working with no issues.
