### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-fs'

### ISSUE THREAD

**Issue by Dario7984** [AtomLinter/linter-stylelint#494]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) package 4.4.7

### Stack Trace

Uncaught Error: Cannot find module 'sb-fs'

```
At module.js:545

Error: Cannot find module 'sb-fs'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.37.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146072)
    at /packages/linter-stylelint/node_modules/atom-package-deps/lib/helpers.js:10:36)
    at /packages/linter-stylelint/node_modules/atom-package-deps/lib/helpers.js:196:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146072)
    at /packages/linter-stylelint/node_modules/atom-package-deps/lib/index.js:10:39)
    at /packages/linter-stylelint/node_modules/atom-package-deps/lib/index.js:55:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146072)
    at installLinterStylelintDeps (/packages/linter-stylelint/lib/index.js:31:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.20.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.32 
intentions 1.1.5 
linter 2.3.0 
linter-stylelint 4.4.7 
linter-ui-default 1.7.1 
pigments 0.40.2 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? It looks like that dependency simply wasn't installed on your machine for some reason.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
