### ISSUE TITLE
Error and stack trace while trying to run stylelint on a file

### ISSUE THREAD

**Issue by kaiyoma** [AtomLinter/linter-stylelint#521]
When I open one of the LESS files in our codebase, I consistently get an error and stack trace from prettier-atom:

```
[Linter] Error running stylelint Error: Column start (10) greater than line length (9) for line 28
    at generateRange (...\packages\prettier-atom\node_modules\atom-linter\lib\index.js:181:11)
    at createRange (.../packages/linter-stylelint/lib/helpers.js:48:10)
    at .../packages/linter-stylelint/lib/helpers.js:76:19
    at Array.map (<anonymous>)
    at parseResults (.../packages/linter-stylelint/lib/helpers.js:68:37)
    at Object.<anonymous> (.../packages/linter-stylelint/lib/helpers.js:263:10)
    at Generator.next (<anonymous>)
    at step (.../packages/linter-stylelint/lib/helpers.js:183:2)
```

Line 28 in the file in question is a completely blank line.

Here's the debug info:

```
Atom version: 1.40.1
prettier-atom version: 0.57.2
prettier: bundled
prettier version: 1.18.2
prettier-eslint version: 9.0.0
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "isDisabledIfNoConfigFile": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "ignoreNodeModules": true
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by Arcanemagus** [comment]
This means that `stylelint` reported a location in the file that didn't actually exist. If you are still seeing this please file a new issue and include a (minimal) example stylelint configuration and file to reproduce this on, thanks!
