### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../duncan/dev/central/web-ui/src/components/common/Component.md"

### ISSUE THREAD

**Issue by dflock** [AtomLinter/linter-stylelint#524]
[Enter steps to reproduce:]

1. Edit a Markdown file

**Atom**: 1.41.0-beta1 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.6
**Thrown From**: [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) package 4.4.9

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../../duncan/dev/central/web-ui/src/components/common/BasicCrudItemForm.md"

```
At /home/dlock/.atom/packages/linter-stylelint/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../../../../duncan/dev/central/web-ui/src/components/common/BasicCrudItemForm.md"
    at throwError (/packages/linter-stylelint/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/linter-stylelint/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/linter-stylelint/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/linter-stylelint/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
     -1:29.5.0 core:cancel (input.hidden-input)
     -1:29.4.0 editor:consolidate-selections (input.hidden-input)
     -1:29.4.0 core:cancel (input.hidden-input)
     -1:28.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:28.9.0 docblockr:parse-enter (input.hidden-input)
     -1:28.9.0 editor:newline (input.hidden-input)
     -1:28.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:28.8.0 docblockr:parse-enter (input.hidden-input)
     -1:28.8.0 editor:newline (input.hidden-input)
     -0:32.6.0 core:delete (input.hidden-input)
     -0:21.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:21.1.0 docblockr:parse-enter (input.hidden-input)
     -0:21.1.0 editor:newline (input.hidden-input)
     -0:21 markdown-writer:insert-new-line (input.hidden-input)
     -0:21 docblockr:parse-enter (input.hidden-input)
     -0:21 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
ansible-snippets 0.2.0 
ariake-dark-syntax 0.2.1 
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
atom-alignment 0.13.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.33.4 
atom-dark-fusion-syntax 2.2.1 
atom-jade 0.3.0 
atom-jinja2 0.6.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-meld 0.3.5 
atom-monokai 0.10.9 
atom-python-run 0.9.7 
atom-special-char-highlighter 0.1.0 
atom-ternjs 0.20.0 
autocomplete-ansible 0.1.24 
autocomplete-asciidoc 0.1.2 
autocomplete-bash-builtins 0.3.5 
autocomplete-font-awesome 1.0.2 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.2 
autocomplete-modules 2.3.0 
autocomplete-project-paths 2.2.0 
autocomplete-python 1.16.0 
bootstrap-vue-snippets 0.12.0 
busy-signal 2.0.1 
character-table 0.4.3 
chmod 0.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
color-picker 2.3.0 
copy-as-rtf 0.9.3 
csscomb 0.3.1 
dash 1.7.1 
data-atom 0.29.1 
docblockr 0.13.7 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
easysort-yaml 0.4.1 
editorconfig 2.5.0 
emmet-simplified 2.6.0 
es6-javascript 1.0.0 
escape-utils 0.5.3 
file-icons 2.1.35 
file-types 1.0.1 
file-watcher 2.0.0 
flatwhite-syntax 0.8.1 
format-shell 2.2.1 
genesis-syntax 1.0.9 
git-blame 1.8.0 
git-hide 1.0.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
hard-wrap 1.7.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
json-converter 0.2.4 
language-ansible 0.2.2 
language-antlr4 0.1.0 
language-asciidoc 1.11.0 
language-babel 2.85.0 
language-batch 0.4.0 
language-csv 1.1.2 
language-diff 0.7.0 
language-docker 1.1.8 
language-dotfiles 1.2.0 
language-dots 0.0.4 
language-generic-config 1.4.0 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-hosts 0.1.2 
language-ini 1.23.0 
language-latex 1.2.0 
language-log 1.10.1 
language-mermaid 0.6.0 
language-mongodb 0.3.1 
language-nginx 0.8.0 
language-pgsql 0.2.3 
language-powershell 5.0.0 
language-pug 0.0.22 
language-restructuredtext 1.1.2 
language-robot-framework 2.4.0 
language-stylus 0.2.0 
language-svg 0.9.2 
language-vue 0.25.0 
last-cursor-position 0.9.3 
less-than-slash 0.19.0 
lines 0.13.1 
linter 2.3.1 
linter-ansible-linting 1.5.0 
linter-ansible-syntax 1.2.3 
linter-csslint 2.0.6 
linter-docker 0.3.2 
linter-eslint 8.5.5 
linter-flake8 2.4.0 
linter-js-standard 7.0.0 
linter-js-yaml 1.4.6 
linter-jsonlint 1.4.0 
linter-less 2.6.0 
linter-markdown 5.2.10 
linter-proselint 3.3.0 
linter-pug 2.0.9 
linter-pycodestyle 2.1.3 
linter-pydocstyle 0.4.7 
linter-ruby 1.3.1 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-javascript 0.9.0 
linter-spell-project 0.2.0 
linter-spell-shellscript 0.2.0 
linter-stylelint 4.4.9 
linter-swagger 0.6.1 
linter-ui-default 1.8.0 
linter-write-good 0.9.3 
linter-xmllint 1.4.4 
MagicPython 1.1.1 
markdown-preview-enhanced 0.16.3 
markdown-preview-plus 3.11.0 
markdown-writer 2.11.9 
material-palenight-syntax 1.5.7 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-linter 2.2.1 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
monokai 0.24.0 
monokai-slate 0.6.0 
moonlight 0.11.0 
nebula-syntax 0.4.5 
nebula-ui 0.9.3 
night-owl-vs-code-syntax 0.10.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
nucleus-dark-ui 0.12.3 
oceanic-next 1.0.0 
oceanic-reef-syntax 0.9.0 
open-terminal-here 2.3.2 
prettier-atom 0.57.3 
pretty-json 2.1.2 
pristine-ui 1.1.11 
pubster-syntax 3.1.0 
pure-syntax 1.0.1 
python-autopep8 0.1.3 
python-indent 1.2.3 
regex-railroad-diagram 0.19.4 
rst-preview-pandoc 0.1.12 
script 3.18.1 
scroll-sync 0.2.4 
set-syntax 0.4.0 
slime 2.4.0 
sort-lines 0.19.0 
split-diff 1.6.1 
ssh-config 0.14.0 
standardjs-snippets 2.6.2 
styri-syntax 1.0.0 
Sublime-Style-Column-Selection 1.7.5 
summer-night-syntax 2.0.1 
susave 0.4.0 
svg-preview 0.14.0 
symbols-tree-view 0.14.0 
text-manipulation 0.6.0 
title-case 0.4.0 
toggle-quotes 1.1.4 
tornado-templates 0.2.0 
tree-view-git-status 1.5.2 
tree-view-scope-lines 0.2.0 
url-open 0.1.0 
Zen 0.18.0 
```

**Comment by Arcanemagus** [comment]
Looks like this was a `linter-markdown` error that just happened to be using the `ignore` module from this package.
